/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Quiz;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author NonhlanhlaMsiza
 */
public class FrameOne extends javax.swing.JFrame {

    int FirstNumber, SecondNumber, Tried, counter, Correct, Result, AnswerOfQ,
            countDown = 60;
    float Result1;
    Timer time;

    /**
     * Creates new form NewJFrame
     */
    //method for the timer
    private void timer() {
        time = new Timer(1000, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                timertxt.setText(String.valueOf(countDown));
                countDown--;
                 if (countDown <= 10) {
                    timertxt.setForeground(Color.red);
                }
                if (countDown <= 0) {
                    JOptionPane.showMessageDialog(null, "Ran out of Time ,Time out!!");
                    time.stop();

                    Checkbtn.setVisible(false);
                    System.exit(0);

                }
            }

        });
        time.start();
    }

    private void addition() {
        Random rand = new Random();
        FirstNumber = rand.nextInt(30);
        SecondNumber = rand.nextInt(30);
        value1.setText(Integer.toString(FirstNumber));

        operand.setText("+");
        value2.setText(Integer.toString(SecondNumber));
        Result = FirstNumber + SecondNumber;

    }

    private void subtraction() {
        Random rand = new Random();
        FirstNumber = rand.nextInt(30);
        SecondNumber = rand.nextInt(30);
        value1.setText(Integer.toString(FirstNumber));

        operand.setText("-");
        value2.setText(Integer.toString(SecondNumber));
        Result = FirstNumber - SecondNumber;
    }

    public void division() {
        Random rand = new Random();
        FirstNumber = rand.nextInt(30);
        SecondNumber = rand.nextInt(30);
        value1.setText(Integer.toString(FirstNumber));

        operand.setText("/");
        value2.setText(Integer.toString(SecondNumber));
        Result1 = FirstNumber / SecondNumber;

    }

    public void multiplication() {
        Random rand = new Random();
        FirstNumber = rand.nextInt(30);
        SecondNumber = rand.nextInt(30);
        value1.setText(Integer.toString(FirstNumber));

        operand.setText("*");
        value2.setText(Integer.toString(SecondNumber));
        Result = FirstNumber * SecondNumber;
    }

    public FrameOne() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        clbl = new javax.swing.JLabel();
        albl = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        value1 = new javax.swing.JLabel();
        operand = new javax.swing.JLabel();
        value2 = new javax.swing.JLabel();
        answerlbl = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        cb1 = new javax.swing.JCheckBox();
        cb2 = new javax.swing.JCheckBox();
        cb3 = new javax.swing.JCheckBox();
        cb4 = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        QR = new javax.swing.JRadioButton();
        Q1 = new javax.swing.JRadioButton();
        Q2 = new javax.swing.JRadioButton();
        Q3 = new javax.swing.JRadioButton();
        Q4 = new javax.swing.JRadioButton();
        Q5 = new javax.swing.JRadioButton();
        Q6 = new javax.swing.JRadioButton();
        Q7 = new javax.swing.JRadioButton();
        Q8 = new javax.swing.JRadioButton();
        Q9 = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        timertxt = new javax.swing.JTextField();
        Exitbtn = new javax.swing.JButton();
        Checkbtn = new javax.swing.JButton();
        Startbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setForeground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Tried:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Correct:");

        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102), 2));

        clbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102), 2));

        albl.setBackground(new java.awt.Color(204, 204, 255));
        albl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 51)));

        jLabel5.setText("=");

        answerlbl.setBackground(new java.awt.Color(204, 204, 255));
        answerlbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        answerlbl.setForeground(new java.awt.Color(0, 0, 0));
        answerlbl.setText("??");
        answerlbl.setBorder(null);

        javax.swing.GroupLayout alblLayout = new javax.swing.GroupLayout(albl);
        albl.setLayout(alblLayout);
        alblLayout.setHorizontalGroup(
            alblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alblLayout.createSequentialGroup()
                .addContainerGap(269, Short.MAX_VALUE)
                .addComponent(value1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(operand)
                .addGap(18, 18, 18)
                .addComponent(value2)
                .addGap(44, 44, 44)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answerlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        alblLayout.setVerticalGroup(
            alblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alblLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(alblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(value1)
                    .addComponent(operand)
                    .addComponent(value2)
                    .addComponent(answerlbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102), 2));

        cb1.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup3.add(cb1);
        cb1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cb1.setText("Addition");
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });

        cb2.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup3.add(cb2);
        cb2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cb2.setText("Subtraction");
        cb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb2ActionPerformed(evt);
            }
        });

        cb3.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup3.add(cb3);
        cb3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cb3.setText("Division");
        cb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb3ActionPerformed(evt);
            }
        });

        cb4.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup3.add(cb4);
        cb4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cb4.setText("Multiplication");
        cb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb4ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Type:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb1)
                    .addComponent(cb2)
                    .addComponent(cb3)
                    .addComponent(cb4))
                .addGap(0, 39, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(10, 10, 10)
                .addComponent(cb1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb4)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102), 2));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("No. of Questions");

        QR.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup2.add(QR);
        QR.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        QR.setText("Random");
        QR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QRMouseClicked(evt);
            }
        });

        Q1.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup2.add(Q1);
        Q1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Q1.setText("1");
        Q1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Q1MouseClicked(evt);
            }
        });

        Q2.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup2.add(Q2);
        Q2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Q2.setText("2");
        Q2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Q2MouseClicked(evt);
            }
        });

        Q3.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup2.add(Q3);
        Q3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Q3.setText("3");
        Q3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Q3MouseClicked(evt);
            }
        });

        Q4.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup2.add(Q4);
        Q4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Q4.setText("4");

        Q5.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup2.add(Q5);
        Q5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Q5.setText("5");
        Q5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Q5MouseClicked(evt);
            }
        });

        Q6.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup2.add(Q6);
        Q6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Q6.setText("6");
        Q6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Q6MouseClicked(evt);
            }
        });

        Q7.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup2.add(Q7);
        Q7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Q7.setText("7");
        Q7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Q7MouseClicked(evt);
            }
        });

        Q8.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup2.add(Q8);
        Q8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Q8.setText("8");
        Q8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Q8MouseClicked(evt);
            }
        });

        Q9.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup2.add(Q9);
        Q9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Q9.setText("9");
        Q9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Q9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(Q1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Q2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(QR)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(Q7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Q8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(22, 22, 22)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(Q4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Q5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Q6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Q3, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                    .addComponent(Q9)))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q1)
                    .addComponent(Q2)
                    .addComponent(Q3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q4)
                    .addComponent(Q5)
                    .addComponent(Q6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q7)
                    .addComponent(Q8)
                    .addComponent(Q9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102), 2));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel9.setText("Timer");

        rb1.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(rb1);
        rb1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rb1.setText("On");
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });

        rb2.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(rb2);
        rb2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rb2.setText("Off");
        rb2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb2MouseClicked(evt);
            }
        });

        timertxt.setEditable(false);
        timertxt.setBackground(new java.awt.Color(255, 255, 255));
        timertxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb1)
                    .addComponent(rb2)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(timertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rb1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rb2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(timertxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Exitbtn.setBackground(new java.awt.Color(102, 0, 204));
        Exitbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Exitbtn.setForeground(new java.awt.Color(255, 255, 255));
        Exitbtn.setText("Exit");
        Exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitbtnActionPerformed(evt);
            }
        });

        Checkbtn.setBackground(new java.awt.Color(102, 0, 204));
        Checkbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Checkbtn.setForeground(new java.awt.Color(255, 255, 255));
        Checkbtn.setText("Check Answer");
        Checkbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckbtnMouseClicked(evt);
            }
        });
        Checkbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckbtnActionPerformed(evt);
            }
        });

        Startbtn.setBackground(new java.awt.Color(102, 0, 204));
        Startbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Startbtn.setForeground(new java.awt.Color(255, 255, 255));
        Startbtn.setText("Start");
        Startbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StartbtnMouseClicked(evt);
            }
        });
        Startbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(Exitbtn)
                .addGap(117, 117, 117)
                .addComponent(Checkbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Startbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(albl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clbl, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)))
                        .addGap(67, 67, 67))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(clbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(albl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Checkbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Startbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Exitbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(85, 85, 85))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:\
        addition();
    }//GEN-LAST:event_cb1ActionPerformed

    private void cb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb2ActionPerformed
        // TODO add your handling code here:
        subtraction();
    }//GEN-LAST:event_cb2ActionPerformed

    private void cb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb3ActionPerformed
        // TODO add your handling code here:
        division();
    }//GEN-LAST:event_cb3ActionPerformed

    private void cb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb4ActionPerformed
        // TODO add your handling code here:
        multiplication();
    }//GEN-LAST:event_cb4ActionPerformed

    private void ExitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitbtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitbtnActionPerformed

    private void StartbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartbtnActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_StartbtnActionPerformed

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
        // TODO add your handling code here:

        rb2.setSelected(false);
        timer();

    }//GEN-LAST:event_rb1ActionPerformed

    private void CheckbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckbtnActionPerformed
        // TODO add your handling code here
        if (cb1.isSelected()) {
            while (counter <= AnswerOfQ) {

                int a = Integer.parseInt(answerlbl.getText().trim());
                String Co, Tr;
                Result = FirstNumber + SecondNumber;
                if (Result == a) {
                    JOptionPane.showMessageDialog(null, "CORRECT!!!");
                    answerlbl.setText(" ");
                    addition();
                    Correct++;
                    counter++;
                    Co = String.valueOf(Correct);
                    clbl.setText(Co);
                    break;

                } else {
                    JOptionPane.showMessageDialog(null, "INCORRECT");
                    answerlbl.setText(" ");
                    addition();
                    Tried++;
                    //counter++;
                    Tr = String.valueOf(Tried);
                    jLabel3.setText(Tr);
                    break;

                }
            }
            if (counter == AnswerOfQ) {
                time.stop();
                Checkbtn.setVisible(false);
                Exitbtn.setVisible(true);

            }
            counter++;

        } else if (cb2.isSelected()) {
            while (counter <= AnswerOfQ) {

                int a = Integer.parseInt(answerlbl.getText().trim());
                String Co, Tr;
                Result = FirstNumber - SecondNumber;
                if (Result == a) {
                    JOptionPane.showMessageDialog(null, "CORRECT!!!");
                    answerlbl.setText(" ");
                    subtraction();

                    Correct++;
                    counter++;
                    Co = String.valueOf(Correct);
                    clbl.setText(Co);

                    break;

                } else {
                    JOptionPane.showMessageDialog(null, "INCORRECT");
                    answerlbl.setText(" ");
                    subtraction();
                    Tried++;
                    //counter++;
                    Tr = String.valueOf(Tried);
                    jLabel3.setText(Tr);
                    break;

                }
            }
            if (counter == AnswerOfQ) {
                time.stop();
                Checkbtn.setVisible(false);
                Exitbtn.setVisible(true);

            }
            counter++;
        } else if (cb3.isSelected()) {
            while (counter <= AnswerOfQ) {

                float a = Float.parseFloat(answerlbl.getText().trim());
                String Co, Tr;
                Result1 = FirstNumber / SecondNumber;
                if (Result1 == a) {
                    JOptionPane.showMessageDialog(null, "CORRECT!!!");
                    answerlbl.setText(" ");
                    division();
                    Correct++;
                    counter++;
                    Co = String.valueOf(Correct);
                    clbl.setText(Co);
                    break;

                } else {
                    JOptionPane.showMessageDialog(null, "INCORRECT");
                    answerlbl.setText(" ");
                    division();
                    Tried++;
                    //counter++;
                    Tr = String.valueOf(Tried);
                    jLabel3.setText(Tr);
                    break;

                }
            }
            if (counter == AnswerOfQ) {
                time.stop();
                Checkbtn.setVisible(false);
                Exitbtn.setVisible(true);

            }
            counter++;
        } else {
            while (counter <= AnswerOfQ) {

                int a = Integer.parseInt(answerlbl.getText().trim());
                String Co, Tr;
                Result = FirstNumber * SecondNumber;
                if (Result == a) {
                    JOptionPane.showMessageDialog(null, "CORRECT!!!");
                    answerlbl.setText(" ");
                    multiplication();
                    Correct++;
                    counter++;
                    Co = String.valueOf(Correct);
                    clbl.setText(Co);
                    break;

                } else {
                    JOptionPane.showMessageDialog(null, "INCORRECT");
                    answerlbl.setText(" ");
                    multiplication();
                    Tried++;
                    //counter++;
                    Tr = String.valueOf(Tried);
                    jLabel3.setText(Tr);
                    break;

                }
            }
            if (counter == AnswerOfQ) {
                time.stop();
                Checkbtn.setVisible(false);
                Exitbtn.setVisible(true);

            }
            counter++;
        }


    }//GEN-LAST:event_CheckbtnActionPerformed

    private void StartbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StartbtnMouseClicked
        // TODO add your handling code here:
        answerlbl.setText(" ");
        Startbtn.setVisible(false);
        if (rb1.isSelected()) {
            timer();
        }
        if (rb2.isSelected()) {
            timertxt.setVisible(false);
        }
    }//GEN-LAST:event_StartbtnMouseClicked

    private void CheckbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckbtnMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_CheckbtnMouseClicked

    private void Q9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Q9MouseClicked
        // TODO add your handling code here:
        AnswerOfQ = 9;


    }//GEN-LAST:event_Q9MouseClicked

    private void Q1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Q1MouseClicked
        // TODO add your handling code here:
        AnswerOfQ = 1;

    }//GEN-LAST:event_Q1MouseClicked

    private void Q2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Q2MouseClicked
        // TODO add your handling code here:
        AnswerOfQ = 2;

    }//GEN-LAST:event_Q2MouseClicked

    private void Q3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Q3MouseClicked
        // TODO add your handling code here:
        AnswerOfQ = 3;

    }//GEN-LAST:event_Q3MouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        // TODO add your handling code here:
        AnswerOfQ = 4;

    }//GEN-LAST:event_jPanel5MouseClicked

    private void Q5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Q5MouseClicked
        // TODO add your handling code here:
        AnswerOfQ = 5;

    }//GEN-LAST:event_Q5MouseClicked

    private void Q6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Q6MouseClicked
        // TODO add your handling code here:
        AnswerOfQ = 6;

    }//GEN-LAST:event_Q6MouseClicked

    private void Q7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Q7MouseClicked
        // TODO add your handling code here:
        AnswerOfQ = 7;

    }//GEN-LAST:event_Q7MouseClicked

    private void Q8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Q8MouseClicked
        // TODO add your handling code here:
        AnswerOfQ = 8;

    }//GEN-LAST:event_Q8MouseClicked

    private void QRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QRMouseClicked
        // TODO add your handling code here:
        Random r = new Random();
        AnswerOfQ = r.nextInt(15);

    }//GEN-LAST:event_QRMouseClicked

    private void rb2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb2MouseClicked
        // TODO add your handling code here:
        rb2.setSelected(false);
    }//GEN-LAST:event_rb2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameOne().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Checkbtn;
    private javax.swing.JButton Exitbtn;
    private javax.swing.JRadioButton Q1;
    private javax.swing.JRadioButton Q2;
    private javax.swing.JRadioButton Q3;
    private javax.swing.JRadioButton Q4;
    private javax.swing.JRadioButton Q5;
    private javax.swing.JRadioButton Q6;
    private javax.swing.JRadioButton Q7;
    private javax.swing.JRadioButton Q8;
    private javax.swing.JRadioButton Q9;
    private javax.swing.JRadioButton QR;
    private javax.swing.JButton Startbtn;
    private javax.swing.JPanel albl;
    private javax.swing.JTextField answerlbl;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JCheckBox cb1;
    private javax.swing.JCheckBox cb2;
    private javax.swing.JCheckBox cb3;
    private javax.swing.JCheckBox cb4;
    private javax.swing.JLabel clbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel operand;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JTextField timertxt;
    private javax.swing.JLabel value1;
    private javax.swing.JLabel value2;
    // End of variables declaration//GEN-END:variables
}
